"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

Icon note:
Star Coin Icon is taken from http://www.cliparthut.com/super-mario-star-coins-clipart-AnSSX1.html (Free to use ClipArt)
The icon represents how precious the time is and also implies that the effect of the app usage will be similar
to that of the coin in Super Mario, as the productivity will increase dramatically
The app has nothing to do with Nintendo and is used only for fun
In case such usage violates Nintendo's rights, the author will use a different icon

Author:
The original author of the Precious app is Anton Vinokurov (www.antonvino.com)
"""

from setuptools import setup

APP = ['Precious.py']
DATA_FILES = ['Precious.xib']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'goldcoin.icns',
    'includes': ['requests']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', "requests"],
)
