"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

Author:
The original author of the Precious app is Anton Vinokurov (www.antonvino.com)
"""

from setuptools import setup

APP = ['Precious.py']
DATA_FILES = ['Precious.xib']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'precious.icns',
    'includes': ['requests']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', "requests"],
)
